# Generated by Django 3.2.8 on 2022-01-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietheatre', '0003_auto_20220121_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='name',
        ),
    ]
