# Generated by Django 3.2.8 on 2022-01-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_auto_20220123_0147'),
        ('movietheatre', '0004_rename_title_movies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(to='cast.Cast'),
        ),
    ]
