# Generated by Django 3.2.8 on 2022-01-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_auto_20220123_0147'),
        ('movietheatre', '0005_movies_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cast.cast'),
        ),
    ]
