# Generated by Django 3.2.8 on 2022-01-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_auto_20220123_0147'),
        ('movietheatre', '0006_auto_20220123_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cast',
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField()),
                ('eighth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eight', to='cast.cast')),
                ('fifth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five', to='cast.cast')),
                ('first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MovieCast', to='cast.cast')),
                ('forth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='cast.cast')),
                ('ninth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nine', to='cast.cast')),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec', to='cast.cast')),
                ('seventh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seven', to='cast.cast')),
                ('sixth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='six', to='cast.cast')),
                ('tenth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ten', to='cast.cast')),
                ('third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thir', to='cast.cast')),
            ],
        ),
    ]
