# Generated by Django 3.2.8 on 2022-01-22 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0002_auto_20220123_0147'),
        ('movietheatre', '0007_auto_20220123_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='eighth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eight', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MovieCast', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='forth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='ninth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nine', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seven', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='six', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='tenth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ten', to='cast.cast'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thir', to='cast.cast'),
        ),
    ]
