# Generated by Django 3.2.8 on 2022-01-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movietheatre', '0008_auto_20220123_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movietheatre.moviecast'),
        ),
    ]
